name: 'Openshift Login'
on:
  push:
  workflow_dispatch:

jobs:
  openshift-job:
    name: OpenShift Login and Test
    runs-on: ubuntu-latest
    env:
      TEST_NAMESPACE: bryant-test
      IMAGE_PATH: quay.io/diagrawa/petclinic:latest
      APP_NAME: petclinic
      APP_PORT: 8080
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1 
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TEST_NAMESPACE }}

      - name: Create and expose an app
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.APP_NAME }}
          image: ${{ env.IMAGE_PATH }}
          namespace: ${{ env.TEST_NAMESPACE }}
          port: ${{ env.APP_PORT }}


  

