name: 'Openshift Login'
on:
  push:
  workflow_dispatch:

jobs:
  login:
    name: OpenShift Login and Test
    runs-on: ubuntu-20.04
    env:
      TEST_NAMESPACE: bryant-test
    
    steps:
      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1 
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TEST_NAMESPACE }}

